"""Repository interfaces (Protocols) — the domain depends on these, not on
SQLAlchemy. Concrete implementations live in the infrastructure layer.
"""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from .entities import (
    Application,
    ApplicationStatus,
    CoverLetter,
    Job,
    Resume,
    SearchRun,
)


@runtime_checkable
class JobRepository(Protocol):
    def add(self, job: Job) -> Job: ...
    def get(self, job_id: int) -> Optional[Job]: ...
    def get_by_fingerprint(self, fingerprint: str) -> Optional[Job]: ...
    def list(
        self,
        country: Optional[str] = None,
        source: Optional[str] = None,
        min_score: Optional[int] = None,
        limit: int = 100,
    ) -> list[Job]: ...
    def update_score(
        self,
        job_id: int,
        score: int,
        breakdown: dict,
        strengths: list[str],
        gaps: list[str],
        recommendation: str,
    ) -> None: ...
    def count(self) -> int: ...
    def count_by_country(self) -> dict[str, int]: ...
    def count_by_role_keyword(self, roles: list[str]) -> dict[str, int]: ...
    def count_high_scoring(self, threshold: int) -> int: ...


@runtime_checkable
class ApplicationRepository(Protocol):
    def add(self, application: Application) -> Application: ...
    def get(self, application_id: int) -> Optional[Application]: ...
    def get_for_job(self, job_id: int) -> Optional[Application]: ...
    def list(self) -> list[Application]: ...
    def update_status(
        self, application_id: int, status: ApplicationStatus, notes: Optional[str]
    ) -> Application: ...
    def pipeline_counts(self) -> dict[str, int]: ...


@runtime_checkable
class ResumeRepository(Protocol):
    def add(self, resume: Resume) -> Resume: ...
    def get(self, resume_id: int) -> Optional[Resume]: ...
    def get_master(self) -> Optional[Resume]: ...
    def list_for_job(self, job_id: int) -> list[Resume]: ...


@runtime_checkable
class CoverLetterRepository(Protocol):
    def add(self, letter: CoverLetter) -> CoverLetter: ...
    def list_for_job(self, job_id: int) -> list[CoverLetter]: ...


@runtime_checkable
class SearchRunRepository(Protocol):
    def add(self, run: SearchRun) -> SearchRun: ...
    def update(self, run: SearchRun) -> SearchRun: ...
    def recent(self, limit: int = 10) -> list[SearchRun]: ...
